
services:
  - type: web
    name: echelonx-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: echelonx-db
          property: connectionString
      - key: PORT
        value: 10000
